
[settings]
	#Time in seconds before the server will restart.
	#Range: 60 ~ 9223372036854775
	shutdownLength = 21600
	#List of Strings and delay before announcement.
	shutdownMessages = ["3600|The server will restart in 60 minutes.", "900|The server will restart in 15 minutes.", "300|The server will restart in 5 minutes.", "15|Restarting in 15 seconds...", "5|Restarting in 5 seconds...", "4|Restarting in 4 seconds...", "3|Restarting in 3 seconds...", "2|Restarting in 2 seconds...", "1|Restarting in 1 second...", "0|Server restarting now!"]

