
#structurize.config.gameplay.comment
[gameplay]
	#structurize.config.maxcachedchanges.comment
	#Range: 0 ~ 100
	maxCachedChanges = 0
	#structurize.config.allowplayerschematics.comment
	allowPlayerSchematics = false
	#structurize.config.ignoreschematicsfromjar.comment
	ignoreSchematicsFromJar = true
	#structurize.config.maxoperationspertick.comment
	#Range: 0 ~ 100000
	maxOperationsPerTick = 1000
	#structurize.config.maxblockschecked.comment
	#Range: 0 ~ 100000
	maxBlocksChecked = 1000
	#structurize.config.maxcachedschematics.comment
	#Range: 0 ~ 100000
	maxCachedSchematics = 100
	#structurize.config.schematicblocklimit.comment
	#Range: 1000 ~ 1000000
	schematicBlockLimit = 100000

