
["General Dimension Options"]
	#
	# Maximum height for clouds to be at.
	# Default is 245.
	#Range: -50 ~ 400
	cloudHeight = 245
	#
	# Lets Nether Portals be able to be created in Ultra Amplified Dimension.
	# Using the portal in this dimension will take you to the Nether but Nether
	# Portals in the Nether will take you to the Overworld instead. So this option
	# is good if you want a second way of escaping the Ultra Amplified Dimension.
	allowNetherPortal = false
	#
	# Adds very heavy fog to make the world look more spooky and limit visibility.
	# This is not the same as distance fog which only applies weakly to chunks in the far distance.
	heavyFog = true
	#
	# Makes leaving the Ultra Amplified dimension by Amplified Portal Block
	# always places you back in the Overworld regardless of which dimension you
	# originally came from. Use this option if this dimension becomes locked in
	# with another dimension so you are stuck teleporting between the two and cannot
	# get back to the Overworld.
	forceExitToOverworld = true

